[package]
name = "acronym-lookup"
description = "Blazingly fast CLI tool for looking up acronyms"
authors = ["mfurak"]
version = "0.25.0"
edition = "2024"

[[bin]]
name = "al"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
